name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 2025.01.17)'
        required: true
        default: '2025.01.17'
      version_code:
        description: 'Version code'
        required: true
        default: '207'

jobs:
  manual_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Enable Gradle Wrapper caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Ruby (for Fastlane)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Fastlane
        run: bundle install

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Build production APK
        run: bundle exec fastlane production_build_apk

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}-${{ github.event.inputs.version_code }}
          release_name: Release v${{ github.event.inputs.version }} (${{ github.event.inputs.version_code }})
          body: |
            Manual Release v${{ github.event.inputs.version }} (${{ github.event.inputs.version_code }})
            
            Changes:
            - Added SATS support with real-time rates
            - SATS uses BTC rate divided by 100M for conversion
            - Real-time crypto rates for BTC and SATS
            - Historical exchange rate storage for transactions
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive 